# NOTE: This file is auto generated by OpenAPI Generator 7.8.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SpoonacularAPI.Model.GetWinePairing200Response do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :pairedWines,
    :pairingText,
    :productMatches
  ]

  @type t :: %__MODULE__{
    :pairedWines => [String.t],
    :pairingText => String.t,
    :productMatches => [SpoonacularAPI.Model.GetWinePairing200ResponseProductMatchesInner.t]
  }

  alias SpoonacularAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:productMatches, :list, SpoonacularAPI.Model.GetWinePairing200ResponseProductMatchesInner)
  end
end

