# NOTE: This file is auto generated by OpenAPI Generator 7.8.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SpoonacularAPI.Model.ProductInformation do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :title,
    :upc,
    :usdaCode,
    :breadcrumbs,
    :imageType,
    :badges,
    :importantBadges,
    :ingredientCount,
    :generatedText,
    :ingredientList,
    :ingredients,
    :likes,
    :aisle,
    :credits,
    :nutrition,
    :price,
    :servings,
    :spoonacularScore
  ]

  @type t :: %__MODULE__{
    :id => integer(),
    :title => String.t,
    :upc => String.t | nil,
    :usdaCode => String.t | nil,
    :breadcrumbs => [String.t],
    :imageType => String.t,
    :badges => [String.t],
    :importantBadges => [String.t],
    :ingredientCount => integer(),
    :generatedText => String.t | nil,
    :ingredientList => String.t,
    :ingredients => [SpoonacularAPI.Model.IngredientBasics.t],
    :likes => float(),
    :aisle => String.t | nil,
    :credits => SpoonacularAPI.Model.ProductInformationCredits.t | nil,
    :nutrition => SpoonacularAPI.Model.SearchGroceryProductsByUpc200ResponseNutrition.t,
    :price => float(),
    :servings => SpoonacularAPI.Model.SearchGroceryProductsByUpc200ResponseServings.t,
    :spoonacularScore => float()
  }

  alias SpoonacularAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:ingredients, :list, SpoonacularAPI.Model.IngredientBasics)
     |> Deserializer.deserialize(:credits, :struct, SpoonacularAPI.Model.ProductInformationCredits)
     |> Deserializer.deserialize(:nutrition, :struct, SpoonacularAPI.Model.SearchGroceryProductsByUpc200ResponseNutrition)
     |> Deserializer.deserialize(:servings, :struct, SpoonacularAPI.Model.SearchGroceryProductsByUpc200ResponseServings)
  end
end

