/**
 * spoonacular API
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over thousands of recipes, thousands of ingredients, 800,000 food products, over 100,000 menu items, and restaurants. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: mail@spoonacular.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric model module.
 * @module model/GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric
 * @version 2.0.2
 */
class GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric {
    /**
     * Constructs a new <code>GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric</code>.
     * @alias module:model/GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric
     * @param unit {String} 
     * @param value {Number} 
     */
    constructor(unit, value) { 
        
        GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric.initialize(this, unit, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, unit, value) { 
        obj['unit'] = unit;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric} obj Optional instance to populate.
     * @return {module:model/GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric} The populated <code>GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric();

            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['unit'] && !(typeof data['unit'] === 'string' || data['unit'] instanceof String)) {
            throw new Error("Expected the field `unit` to be a primitive type in the JSON string but got " + data['unit']);
        }

        return true;
    }


}

GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric.RequiredProperties = ["unit", "value"];

/**
 * @member {String} unit
 */
GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric.prototype['unit'] = undefined;

/**
 * @member {Number} value
 */
GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric.prototype['value'] = undefined;






export default GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric;

