{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import Spoonacular.Model
import Spoonacular.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 10) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy FoodIngredientsMapProducts)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject1)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject10)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject2)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject3)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject4)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject5)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject6)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject7)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject8)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject9)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse200)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2001)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20010)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20010Amount)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20010AmountMetric)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20010Ingredients)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20011)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20011Ingredients)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20012)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20013)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20013Ingredients)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20013Ingredients1)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20013ParsedInstructions)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20013Steps)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20014)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20015)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20016)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20017)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20018)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20018Dishes)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20018Ingredients)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20019)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2002)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20020)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20021)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20021Calories)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20021CaloriesConfidenceRange95Percent)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20022)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20022Nutrition)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20023)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20023Ingredients)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20024)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20025)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20025Results)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20026)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20027)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20028)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20028Ingredients)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20028Nutrition)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20028Servings)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20029)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20029CustomFoods)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2003)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20030)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20030Ingredients)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20031)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20031ComparableProducts)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20031ComparableProductsProtein)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20032)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20032Results)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20033)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20034)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20035)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20035MenuItems)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20036)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20037)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20037Nutrients)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20038)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20038Days)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20038Items)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20038NutritionSummary)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20038NutritionSummaryNutrients)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20038Value)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20039)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2003ExtendedIngredients)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2003Measures)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2003MeasuresMetric)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2003WinePairing)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2003WinePairingProductMatches)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2004)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20040)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20040Items)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20040Value)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20041)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20041Days)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20041Items)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20041Value)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20042)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20042Aisles)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20042Items)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20042Measures)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20043)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20044)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20045)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20045ProductMatches)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20046)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20047)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20047RecommendedWines)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20048)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20049)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20049Category)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20049Nutrition)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20049NutritionCalories)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20049NutritionCaloriesConfidenceRange95Percent)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20049Recipes)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2005)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20050)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20051)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20052)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20053)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20053Results)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20053SearchResults)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20054)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20054Videos)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20055)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20056)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20057)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20057Suggests)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2006)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2006Recipes)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2007)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2008)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2009)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse200Results)
      propMimeEq MimeJSON (Proxy :: Proxy RecipesFindByIngredientsMissedIngredients)
      propMimeEq MimeJSON (Proxy :: Proxy RecipesParseIngredientsEstimatedCost)
      propMimeEq MimeJSON (Proxy :: Proxy RecipesParseIngredientsNutrition)
      propMimeEq MimeJSON (Proxy :: Proxy RecipesParseIngredientsNutritionCaloricBreakdown)
      propMimeEq MimeJSON (Proxy :: Proxy RecipesParseIngredientsNutritionNutrients)
      propMimeEq MimeJSON (Proxy :: Proxy RecipesParseIngredientsNutritionProperties)
      propMimeEq MimeJSON (Proxy :: Proxy RecipesParseIngredientsNutritionWeightPerServing)
      
