{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import Spoonacular.Model
import Spoonacular.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 10) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy AddMealPlanTemplate200Response)
      propMimeEq MimeJSON (Proxy :: Proxy AddMealPlanTemplate200ResponseItemsInner)
      propMimeEq MimeJSON (Proxy :: Proxy AddMealPlanTemplate200ResponseItemsInnerValue)
      propMimeEq MimeJSON (Proxy :: Proxy AddToMealPlanRequest)
      propMimeEq MimeJSON (Proxy :: Proxy AddToMealPlanRequest1)
      propMimeEq MimeJSON (Proxy :: Proxy AddToMealPlanRequest1Value)
      propMimeEq MimeJSON (Proxy :: Proxy AddToMealPlanRequest1ValueIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy AddToShoppingListRequest)
      propMimeEq MimeJSON (Proxy :: Proxy AnalyzeARecipeSearchQuery200Response)
      propMimeEq MimeJSON (Proxy :: Proxy AnalyzeARecipeSearchQuery200ResponseDishesInner)
      propMimeEq MimeJSON (Proxy :: Proxy AnalyzeARecipeSearchQuery200ResponseIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy AnalyzeRecipeInstructions200Response)
      propMimeEq MimeJSON (Proxy :: Proxy AnalyzeRecipeInstructions200ResponseIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy AnalyzeRecipeInstructions200ResponseParsedInstructionsInner)
      propMimeEq MimeJSON (Proxy :: Proxy AnalyzeRecipeInstructions200ResponseParsedInstructionsInnerStepsInner)
      propMimeEq MimeJSON (Proxy :: Proxy AnalyzeRecipeInstructions200ResponseParsedInstructionsInnerStepsInnerIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy AutocompleteIngredientSearch200ResponseInner)
      propMimeEq MimeJSON (Proxy :: Proxy AutocompleteMenuItemSearch200Response)
      propMimeEq MimeJSON (Proxy :: Proxy AutocompleteProductSearch200Response)
      propMimeEq MimeJSON (Proxy :: Proxy AutocompleteProductSearch200ResponseResultsInner)
      propMimeEq MimeJSON (Proxy :: Proxy AutocompleteRecipeSearch200ResponseInner)
      propMimeEq MimeJSON (Proxy :: Proxy ClassifyCuisine200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ClassifyGroceryProduct200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ClassifyGroceryProductBulk200ResponseInner)
      propMimeEq MimeJSON (Proxy :: Proxy ClassifyGroceryProductBulkRequestInner)
      propMimeEq MimeJSON (Proxy :: Proxy ClassifyGroceryProductRequest)
      propMimeEq MimeJSON (Proxy :: Proxy ClearMealPlanDayRequest)
      propMimeEq MimeJSON (Proxy :: Proxy ComputeGlycemicLoad200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ComputeGlycemicLoad200ResponseIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy ComputeGlycemicLoadRequest)
      propMimeEq MimeJSON (Proxy :: Proxy ComputeIngredientAmount200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ConnectUser200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ConnectUserRequest)
      propMimeEq MimeJSON (Proxy :: Proxy ConvertAmounts200Response)
      propMimeEq MimeJSON (Proxy :: Proxy CreateRecipeCard200Response)
      propMimeEq MimeJSON (Proxy :: Proxy DeleteFromMealPlanRequest)
      propMimeEq MimeJSON (Proxy :: Proxy DetectFoodInText200Response)
      propMimeEq MimeJSON (Proxy :: Proxy DetectFoodInText200ResponseAnnotationsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GenerateMealPlan200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GenerateMealPlan200ResponseNutrients)
      propMimeEq MimeJSON (Proxy :: Proxy GenerateShoppingList200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GenerateShoppingListRequest)
      propMimeEq MimeJSON (Proxy :: Proxy GetARandomFoodJoke200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetAnalyzedRecipeInstructions200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetAnalyzedRecipeInstructions200ResponseIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetAnalyzedRecipeInstructions200ResponseParsedInstructionsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetAnalyzedRecipeInstructions200ResponseParsedInstructionsInnerStepsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetAnalyzedRecipeInstructions200ResponseParsedInstructionsInnerStepsInnerIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetComparableProducts200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetComparableProducts200ResponseComparableProducts)
      propMimeEq MimeJSON (Proxy :: Proxy GetComparableProducts200ResponseComparableProductsProteinInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetConversationSuggests200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetConversationSuggests200ResponseSuggests)
      propMimeEq MimeJSON (Proxy :: Proxy GetConversationSuggests200ResponseSuggestsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetDishPairingForWine200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetIngredientInformation200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetIngredientInformation200ResponseNutrition)
      propMimeEq MimeJSON (Proxy :: Proxy GetIngredientSubstitutes200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetMealPlanTemplate200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetMealPlanTemplate200ResponseDaysInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetMealPlanTemplate200ResponseDaysInnerItemsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetMealPlanTemplate200ResponseDaysInnerItemsInnerValue)
      propMimeEq MimeJSON (Proxy :: Proxy GetMealPlanTemplates200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetMealPlanWeek200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetMealPlanWeek200ResponseDaysInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetMealPlanWeek200ResponseDaysInnerItemsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetMealPlanWeek200ResponseDaysInnerItemsInnerValue)
      propMimeEq MimeJSON (Proxy :: Proxy GetMealPlanWeek200ResponseDaysInnerNutritionSummary)
      propMimeEq MimeJSON (Proxy :: Proxy GetMealPlanWeek200ResponseDaysInnerNutritionSummaryNutrientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetMenuItemInformation200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetProductInformation200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetProductInformation200ResponseIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetRandomFoodTrivia200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetRandomRecipes200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetRandomRecipes200ResponseRecipesInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeEquipmentByID200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeEquipmentByID200ResponseEquipmentInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeInformation200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeInformation200ResponseExtendedIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeInformation200ResponseExtendedIngredientsInnerMeasures)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeInformation200ResponseExtendedIngredientsInnerMeasuresMetric)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeInformation200ResponseWinePairing)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeInformation200ResponseWinePairingProductMatchesInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeInformationBulk200ResponseInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeIngredientsByID200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeIngredientsByID200ResponseIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeNutritionWidgetByID200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeNutritionWidgetByID200ResponseBadInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeNutritionWidgetByID200ResponseGoodInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipePriceBreakdownByID200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipePriceBreakdownByID200ResponseIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmount)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric)
      propMimeEq MimeJSON (Proxy :: Proxy GetRecipeTasteByID200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetShoppingList200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetShoppingList200ResponseAislesInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetShoppingList200ResponseAislesInnerItemsInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetShoppingList200ResponseAislesInnerItemsInnerMeasures)
      propMimeEq MimeJSON (Proxy :: Proxy GetSimilarRecipes200ResponseInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetWineDescription200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetWinePairing200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetWinePairing200ResponseProductMatchesInner)
      propMimeEq MimeJSON (Proxy :: Proxy GetWineRecommendation200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GetWineRecommendation200ResponseRecommendedWinesInner)
      propMimeEq MimeJSON (Proxy :: Proxy GuessNutritionByDishName200Response)
      propMimeEq MimeJSON (Proxy :: Proxy GuessNutritionByDishName200ResponseCalories)
      propMimeEq MimeJSON (Proxy :: Proxy GuessNutritionByDishName200ResponseCaloriesConfidenceRange95Percent)
      propMimeEq MimeJSON (Proxy :: Proxy ImageAnalysisByURL200Response)
      propMimeEq MimeJSON (Proxy :: Proxy ImageAnalysisByURL200ResponseCategory)
      propMimeEq MimeJSON (Proxy :: Proxy ImageAnalysisByURL200ResponseNutrition)
      propMimeEq MimeJSON (Proxy :: Proxy ImageAnalysisByURL200ResponseNutritionCalories)
      propMimeEq MimeJSON (Proxy :: Proxy ImageAnalysisByURL200ResponseNutritionCaloriesConfidenceRange95Percent)
      propMimeEq MimeJSON (Proxy :: Proxy ImageAnalysisByURL200ResponseRecipesInner)
      propMimeEq MimeJSON (Proxy :: Proxy ImageClassificationByURL200Response)
      propMimeEq MimeJSON (Proxy :: Proxy IngredientSearch200Response)
      propMimeEq MimeJSON (Proxy :: Proxy IngredientSearch200ResponseResultsInner)
      propMimeEq MimeJSON (Proxy :: Proxy MapIngredientsToGroceryProducts200ResponseInner)
      propMimeEq MimeJSON (Proxy :: Proxy MapIngredientsToGroceryProducts200ResponseInnerProductsInner)
      propMimeEq MimeJSON (Proxy :: Proxy MapIngredientsToGroceryProductsRequest)
      propMimeEq MimeJSON (Proxy :: Proxy ParseIngredients200ResponseInner)
      propMimeEq MimeJSON (Proxy :: Proxy ParseIngredients200ResponseInnerEstimatedCost)
      propMimeEq MimeJSON (Proxy :: Proxy ParseIngredients200ResponseInnerNutrition)
      propMimeEq MimeJSON (Proxy :: Proxy ParseIngredients200ResponseInnerNutritionCaloricBreakdown)
      propMimeEq MimeJSON (Proxy :: Proxy ParseIngredients200ResponseInnerNutritionNutrientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy ParseIngredients200ResponseInnerNutritionPropertiesInner)
      propMimeEq MimeJSON (Proxy :: Proxy ParseIngredients200ResponseInnerNutritionWeightPerServing)
      propMimeEq MimeJSON (Proxy :: Proxy QuickAnswer200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchAllFood200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchAllFood200ResponseSearchResultsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchAllFood200ResponseSearchResultsInnerResultsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchCustomFoods200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchCustomFoods200ResponseCustomFoodsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchFoodVideos200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchFoodVideos200ResponseVideosInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchGroceryProducts200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchGroceryProductsByUPC200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchGroceryProductsByUPC200ResponseIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchGroceryProductsByUPC200ResponseNutrition)
      propMimeEq MimeJSON (Proxy :: Proxy SearchGroceryProductsByUPC200ResponseServings)
      propMimeEq MimeJSON (Proxy :: Proxy SearchMenuItems200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchMenuItems200ResponseMenuItemsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRecipes200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRecipes200ResponseResultsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRecipesByIngredients200ResponseInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRecipesByIngredients200ResponseInnerMissedIngredientsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchRecipesByNutrients200ResponseInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchSiteContent200Response)
      propMimeEq MimeJSON (Proxy :: Proxy SearchSiteContent200ResponseArticlesInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchSiteContent200ResponseGroceryProductsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner)
      propMimeEq MimeJSON (Proxy :: Proxy SummarizeRecipe200Response)
      propMimeEq MimeJSON (Proxy :: Proxy TalkToChatbot200Response)
      
