export * from './default.service';
import { DefaultService } from './default.service';
export * from './ingredients.service';
import { IngredientsService } from './ingredients.service';
export * from './mealPlanning.service';
import { MealPlanningService } from './mealPlanning.service';
export * from './menuItems.service';
import { MenuItemsService } from './menuItems.service';
export * from './misc.service';
import { MiscService } from './misc.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './recipes.service';
import { RecipesService } from './recipes.service';
export * from './wine.service';
import { WineService } from './wine.service';
export const APIS = [DefaultService, IngredientsService, MealPlanningService, MenuItemsService, MiscService, ProductsService, RecipesService, WineService];
