<?php
/**
 * MenuItemsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  com.spoonacular.client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * spoonacular API
 *
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@spoonacular.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace com.spoonacular.client;

use \com.spoonacular.client\Configuration;
use \com.spoonacular.client\ApiException;
use \com.spoonacular.client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MenuItemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  com.spoonacular.client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MenuItemsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for autocompleteMenuItemSearch
     *
     * Autocomplete Menu Item Search.
     *
     */
    public function testAutocompleteMenuItemSearch()
    {
    }

    /**
     * Test case for getMenuItemInformation
     *
     * Get Menu Item Information.
     *
     */
    public function testGetMenuItemInformation()
    {
    }

    /**
     * Test case for menuItemNutritionByIDImage
     *
     * Menu Item Nutrition by ID Image.
     *
     */
    public function testMenuItemNutritionByIDImage()
    {
    }

    /**
     * Test case for menuItemNutritionLabelImage
     *
     * Menu Item Nutrition Label Image.
     *
     */
    public function testMenuItemNutritionLabelImage()
    {
    }

    /**
     * Test case for menuItemNutritionLabelWidget
     *
     * Menu Item Nutrition Label Widget.
     *
     */
    public function testMenuItemNutritionLabelWidget()
    {
    }

    /**
     * Test case for searchMenuItems
     *
     * Search Menu Items.
     *
     */
    public function testSearchMenuItems()
    {
    }

    /**
     * Test case for visualizeMenuItemNutritionByID
     *
     * Menu Item Nutrition by ID Widget.
     *
     */
    public function testVisualizeMenuItemNutritionByID()
    {
    }
}
