# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule com.spoonacular.client.Model.AnalyzeARecipeSearchQuery200Response do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :dishes,
    :ingredients,
    :cuisines,
    :modifiers
  ]

  @type t :: %__MODULE__{
    :dishes => [com.spoonacular.client.Model.AnalyzeARecipeSearchQuery200ResponseDishesInner.t],
    :ingredients => [com.spoonacular.client.Model.AnalyzeARecipeSearchQuery200ResponseIngredientsInner.t],
    :cuisines => [String.t],
    :modifiers => [String.t]
  }
end

defimpl Poison.Decoder, for: com.spoonacular.client.Model.AnalyzeARecipeSearchQuery200Response do
  import com.spoonacular.client.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:dishes, :list, com.spoonacular.client.Model.AnalyzeARecipeSearchQuery200ResponseDishesInner, options)
    |> deserialize(:ingredients, :list, com.spoonacular.client.Model.AnalyzeARecipeSearchQuery200ResponseIngredientsInner, options)
  end
end

