/**
 * spoonacular API
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@spoonacular.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIInline_response_200_2.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIInline_response_200_2::OAIInline_response_200_2(QString json) {
    this->init();
    this->fromJson(json);
}

OAIInline_response_200_2::OAIInline_response_200_2() {
    this->init();
}

OAIInline_response_200_2::~OAIInline_response_200_2() {

}

void
OAIInline_response_200_2::init() {
    
    m_calories_isSet = false;
    m_calories_isValid = false;
    
    m_carbs_isSet = false;
    m_carbs_isValid = false;
    
    m_fat_isSet = false;
    m_fat_isValid = false;
    
    m_id_isSet = false;
    m_id_isValid = false;
    
    m_image_isSet = false;
    m_image_isValid = false;
    
    m_image_type_isSet = false;
    m_image_type_isValid = false;
    
    m_protein_isSet = false;
    m_protein_isValid = false;
    
    m_title_isSet = false;
    m_title_isValid = false;
    }

void
OAIInline_response_200_2::fromJson(QString jsonString) {
    QByteArray array (jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void
OAIInline_response_200_2::fromJsonObject(QJsonObject json) {
    
    m_calories_isValid = ::OpenAPI::fromJsonValue(calories, json[QString("calories")]);
    
    
    m_carbs_isValid = ::OpenAPI::fromJsonValue(carbs, json[QString("carbs")]);
    
    
    m_fat_isValid = ::OpenAPI::fromJsonValue(fat, json[QString("fat")]);
    
    
    m_id_isValid = ::OpenAPI::fromJsonValue(id, json[QString("id")]);
    
    
    m_image_isValid = ::OpenAPI::fromJsonValue(image, json[QString("image")]);
    
    
    m_image_type_isValid = ::OpenAPI::fromJsonValue(image_type, json[QString("imageType")]);
    
    
    m_protein_isValid = ::OpenAPI::fromJsonValue(protein, json[QString("protein")]);
    
    
    m_title_isValid = ::OpenAPI::fromJsonValue(title, json[QString("title")]);
    
    
}

QString
OAIInline_response_200_2::asJson () const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIInline_response_200_2::asJsonObject() const {
    QJsonObject obj;
	if(calories.isSet()){
        obj.insert(QString("calories"), ::OpenAPI::toJsonValue(calories));
    }
	if(m_carbs_isSet){
        obj.insert(QString("carbs"), ::OpenAPI::toJsonValue(carbs));
    }
	if(m_fat_isSet){
        obj.insert(QString("fat"), ::OpenAPI::toJsonValue(fat));
    }
	if(m_id_isSet){
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(id));
    }
	if(m_image_isSet){
        obj.insert(QString("image"), ::OpenAPI::toJsonValue(image));
    }
	if(m_image_type_isSet){
        obj.insert(QString("imageType"), ::OpenAPI::toJsonValue(image_type));
    }
	if(m_protein_isSet){
        obj.insert(QString("protein"), ::OpenAPI::toJsonValue(protein));
    }
	if(m_title_isSet){
        obj.insert(QString("title"), ::OpenAPI::toJsonValue(title));
    }
    return obj;
}


OAINumber
OAIInline_response_200_2::getCalories() const {
    return calories;
}
void
OAIInline_response_200_2::setCalories(const OAINumber &calories) {
    this->calories = calories;
    this->m_calories_isSet = true;
}


QString
OAIInline_response_200_2::getCarbs() const {
    return carbs;
}
void
OAIInline_response_200_2::setCarbs(const QString &carbs) {
    this->carbs = carbs;
    this->m_carbs_isSet = true;
}


QString
OAIInline_response_200_2::getFat() const {
    return fat;
}
void
OAIInline_response_200_2::setFat(const QString &fat) {
    this->fat = fat;
    this->m_fat_isSet = true;
}


qint32
OAIInline_response_200_2::getId() const {
    return id;
}
void
OAIInline_response_200_2::setId(const qint32 &id) {
    this->id = id;
    this->m_id_isSet = true;
}


QString
OAIInline_response_200_2::getImage() const {
    return image;
}
void
OAIInline_response_200_2::setImage(const QString &image) {
    this->image = image;
    this->m_image_isSet = true;
}


QString
OAIInline_response_200_2::getImageType() const {
    return image_type;
}
void
OAIInline_response_200_2::setImageType(const QString &image_type) {
    this->image_type = image_type;
    this->m_image_type_isSet = true;
}


QString
OAIInline_response_200_2::getProtein() const {
    return protein;
}
void
OAIInline_response_200_2::setProtein(const QString &protein) {
    this->protein = protein;
    this->m_protein_isSet = true;
}


QString
OAIInline_response_200_2::getTitle() const {
    return title;
}
void
OAIInline_response_200_2::setTitle(const QString &title) {
    this->title = title;
    this->m_title_isSet = true;
}

bool
OAIInline_response_200_2::isSet() const {
    bool isObjectUpdated = false;
    do{ 
        if(calories.isSet()){ isObjectUpdated = true; break;}
    
        if(m_carbs_isSet){ isObjectUpdated = true; break;}
    
        if(m_fat_isSet){ isObjectUpdated = true; break;}
    
        if(m_id_isSet){ isObjectUpdated = true; break;}
    
        if(m_image_isSet){ isObjectUpdated = true; break;}
    
        if(m_image_type_isSet){ isObjectUpdated = true; break;}
    
        if(m_protein_isSet){ isObjectUpdated = true; break;}
    
        if(m_title_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}

bool
OAIInline_response_200_2::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_calories_isValid && m_carbs_isValid && m_fat_isValid && m_id_isValid && m_image_isValid && m_image_type_isValid && m_protein_isValid && m_title_isValid && true;
}

}

