/**
 * spoonacular API
 * The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@spoonacular.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200_38_days.h
 *
 * 
 */

#ifndef OAIInline_response_200_38_days_H
#define OAIInline_response_200_38_days_H

#include <QJsonObject>


#include "com.spoonacular.client.model\OAIInline_response_200_38_items.h"
#include "com.spoonacular.client.model\OAIInline_response_200_38_nutritionSummary.h"
#include "com.spoonacular.client.model\OAINumber.h"
#include <QList>
#include <QString>

#include "OAIObject.h"
#include "OAIEnum.h"

namespace OpenAPI {

class OAIInline_response_200_38_days: public OAIObject {
public:
    OAIInline_response_200_38_days();
    OAIInline_response_200_38_days(QString json);
    ~OAIInline_response_200_38_days() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    OAIInline_response_200_38_nutritionSummary getNutritionSummary() const;
    void setNutritionSummary(const OAIInline_response_200_38_nutritionSummary &nutrition_summary);

    
    OAIInline_response_200_38_nutritionSummary getNutritionSummaryBreakfast() const;
    void setNutritionSummaryBreakfast(const OAIInline_response_200_38_nutritionSummary &nutrition_summary_breakfast);

    
    OAIInline_response_200_38_nutritionSummary getNutritionSummaryLunch() const;
    void setNutritionSummaryLunch(const OAIInline_response_200_38_nutritionSummary &nutrition_summary_lunch);

    
    OAIInline_response_200_38_nutritionSummary getNutritionSummaryDinner() const;
    void setNutritionSummaryDinner(const OAIInline_response_200_38_nutritionSummary &nutrition_summary_dinner);

    
    OAINumber getDate() const;
    void setDate(const OAINumber &date);

    
    QString getDay() const;
    void setDay(const QString &day);

    
    QList<OAIInline_response_200_38_items> getItems() const;
    void setItems(const QList<OAIInline_response_200_38_items> &items);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    OAIInline_response_200_38_nutritionSummary nutrition_summary;
    bool m_nutrition_summary_isSet;
    bool m_nutrition_summary_isValid;
    
    OAIInline_response_200_38_nutritionSummary nutrition_summary_breakfast;
    bool m_nutrition_summary_breakfast_isSet;
    bool m_nutrition_summary_breakfast_isValid;
    
    OAIInline_response_200_38_nutritionSummary nutrition_summary_lunch;
    bool m_nutrition_summary_lunch_isSet;
    bool m_nutrition_summary_lunch_isValid;
    
    OAIInline_response_200_38_nutritionSummary nutrition_summary_dinner;
    bool m_nutrition_summary_dinner_isSet;
    bool m_nutrition_summary_dinner_isValid;
    
    OAINumber date;
    bool m_date_isSet;
    bool m_date_isValid;
    
    QString day;
    bool m_day_isSet;
    bool m_day_isValid;
    
    QList<OAIInline_response_200_38_items> items;
    bool m_items_isSet;
    bool m_items_isValid;
    
    };

}

#endif // OAIInline_response_200_38_days_H
