/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spoonacular.client.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.spoonacular.client.model.ClassifyGroceryProduct200Response

class ClassifyGroceryProduct200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ClassifyGroceryProduct200Response
        //val modelInstance = ClassifyGroceryProduct200Response()

        // to test the property `cleanTitle`
        should("test cleanTitle") {
            // uncomment below to test the property
            //modelInstance.cleanTitle shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `category`
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `breadcrumbs`
        should("test breadcrumbs") {
            // uncomment below to test the property
            //modelInstance.breadcrumbs shouldBe ("TODO")
        }

        // to test the property `usdaCode`
        should("test usdaCode") {
            // uncomment below to test the property
            //modelInstance.usdaCode shouldBe ("TODO")
        }

    }
}
