/*
spoonacular API

The spoonacular Nutrition, Recipe, and Food API allows you to access over thousands of recipes, thousands of ingredients, 800,000 food products, over 100,000 menu items, and restaurants. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.

API version: 2.0.1
Contact: mail@spoonacular.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spoonacular

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IngredientInformationNutritionPropertiesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IngredientInformationNutritionPropertiesInner{}

// IngredientInformationNutritionPropertiesInner struct for IngredientInformationNutritionPropertiesInner
type IngredientInformationNutritionPropertiesInner struct {
	Name string `json:"name"`
	Amount float32 `json:"amount"`
	Unit string `json:"unit"`
}

type _IngredientInformationNutritionPropertiesInner IngredientInformationNutritionPropertiesInner

// NewIngredientInformationNutritionPropertiesInner instantiates a new IngredientInformationNutritionPropertiesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngredientInformationNutritionPropertiesInner(name string, amount float32, unit string) *IngredientInformationNutritionPropertiesInner {
	this := IngredientInformationNutritionPropertiesInner{}
	this.Name = name
	this.Amount = amount
	this.Unit = unit
	return &this
}

// NewIngredientInformationNutritionPropertiesInnerWithDefaults instantiates a new IngredientInformationNutritionPropertiesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngredientInformationNutritionPropertiesInnerWithDefaults() *IngredientInformationNutritionPropertiesInner {
	this := IngredientInformationNutritionPropertiesInner{}
	return &this
}

// GetName returns the Name field value
func (o *IngredientInformationNutritionPropertiesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IngredientInformationNutritionPropertiesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IngredientInformationNutritionPropertiesInner) SetName(v string) {
	o.Name = v
}

// GetAmount returns the Amount field value
func (o *IngredientInformationNutritionPropertiesInner) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *IngredientInformationNutritionPropertiesInner) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *IngredientInformationNutritionPropertiesInner) SetAmount(v float32) {
	o.Amount = v
}

// GetUnit returns the Unit field value
func (o *IngredientInformationNutritionPropertiesInner) GetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *IngredientInformationNutritionPropertiesInner) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *IngredientInformationNutritionPropertiesInner) SetUnit(v string) {
	o.Unit = v
}

func (o IngredientInformationNutritionPropertiesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IngredientInformationNutritionPropertiesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["amount"] = o.Amount
	toSerialize["unit"] = o.Unit
	return toSerialize, nil
}

func (o *IngredientInformationNutritionPropertiesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"amount",
		"unit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIngredientInformationNutritionPropertiesInner := _IngredientInformationNutritionPropertiesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIngredientInformationNutritionPropertiesInner)

	if err != nil {
		return err
	}

	*o = IngredientInformationNutritionPropertiesInner(varIngredientInformationNutritionPropertiesInner)

	return err
}

type NullableIngredientInformationNutritionPropertiesInner struct {
	value *IngredientInformationNutritionPropertiesInner
	isSet bool
}

func (v NullableIngredientInformationNutritionPropertiesInner) Get() *IngredientInformationNutritionPropertiesInner {
	return v.value
}

func (v *NullableIngredientInformationNutritionPropertiesInner) Set(val *IngredientInformationNutritionPropertiesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableIngredientInformationNutritionPropertiesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableIngredientInformationNutritionPropertiesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngredientInformationNutritionPropertiesInner(val *IngredientInformationNutritionPropertiesInner) *NullableIngredientInformationNutritionPropertiesInner {
	return &NullableIngredientInformationNutritionPropertiesInner{value: val, isSet: true}
}

func (v NullableIngredientInformationNutritionPropertiesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngredientInformationNutritionPropertiesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


