/*
spoonacular API

The spoonacular Nutrition, Recipe, and Food API allows you to access over thousands of recipes, thousands of ingredients, 800,000 food products, over 100,000 menu items, and restaurants. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.

API version: 1.1
Contact: mail@spoonacular.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner struct for SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner
type SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner struct {
	Key string `json:"key"`
	Value string `json:"value"`
}

// NewSearchSiteContent200ResponseGroceryProductsInnerDataPointsInner instantiates a new SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchSiteContent200ResponseGroceryProductsInnerDataPointsInner(key string, value string) *SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner {
	this := SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner{}
	this.Key = key
	this.Value = value
	return &this
}

// NewSearchSiteContent200ResponseGroceryProductsInnerDataPointsInnerWithDefaults instantiates a new SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchSiteContent200ResponseGroceryProductsInnerDataPointsInnerWithDefaults() *SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner {
	this := SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner{}
	return &this
}

// GetKey returns the Key field value
func (o *SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) SetValue(v string) {
	o.Value = v
}

func (o SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["key"] = o.Key
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableSearchSiteContent200ResponseGroceryProductsInnerDataPointsInner struct {
	value *SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner
	isSet bool
}

func (v NullableSearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) Get() *SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner {
	return v.value
}

func (v *NullableSearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) Set(val *SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchSiteContent200ResponseGroceryProductsInnerDataPointsInner(val *SearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) *NullableSearchSiteContent200ResponseGroceryProductsInnerDataPointsInner {
	return &NullableSearchSiteContent200ResponseGroceryProductsInnerDataPointsInner{value: val, isSet: true}
}

func (v NullableSearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchSiteContent200ResponseGroceryProductsInnerDataPointsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


