--[[
  spoonacular API
 
  The spoonacular Nutrition, Recipe, and Food API allows you to access over 380,000 recipes, thousands of ingredients, 800,000 food products, and 100,000 menu items. Our food ontology and semantic recipe search engine makes it possible to search for recipes using natural language queries, such as \"gluten free brownies without sugar\" or \"low fat vegan cupcakes.\" You can automatically calculate the nutritional information for any recipe, analyze recipe costs, visualize ingredient lists, find recipes for what's in your fridge, find recipes based on special diets, nutritional requirements, or favorite ingredients, classify recipes into types and cuisines, convert ingredient amounts, or even compute an entire meal plan. With our powerful API, you can create many kinds of food and especially nutrition apps.  Special diets/dietary requirements currently available include: vegan, vegetarian, pescetarian, gluten free, grain free, dairy free, high protein, whole 30, low sodium, low carb, Paleo, ketogenic, FODMAP, and Primal.
 
  The version of the OpenAPI document: 1.0
  Contact: mail@spoonacular.com
  Generated by: https://openapi-generator.tech
]]

-- _recipes_find_by_ingredients_missed_ingredients class
local _recipes_find_by_ingredients_missed_ingredients = {}
local _recipes_find_by_ingredients_missed_ingredients_mt = {
	__name = "_recipes_find_by_ingredients_missed_ingredients";
	__index = _recipes_find_by_ingredients_missed_ingredients;
}

local function cast__recipes_find_by_ingredients_missed_ingredients(t)
	return setmetatable(t, _recipes_find_by_ingredients_missed_ingredients_mt)
end

local function new__recipes_find_by_ingredients_missed_ingredients(aisle, amount, id, image, meta, name, original, original_name, unit, unit_long, unit_short)
	return cast__recipes_find_by_ingredients_missed_ingredients({
		["aisle"] = aisle;
		["amount"] = amount;
		["id"] = id;
		["image"] = image;
		["meta"] = meta;
		["name"] = name;
		["original"] = original;
		["originalName"] = original_name;
		["unit"] = unit;
		["unitLong"] = unit_long;
		["unitShort"] = unit_short;
	})
end

return {
	cast = cast__recipes_find_by_ingredients_missed_ingredients;
	new = new__recipes_find_by_ingredients_missed_ingredients;
}
