/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spoonacular.client.model

import com.spoonacular.client.model.GetAnalyzedRecipeInstructions200ResponseIngredientsInner
import com.spoonacular.client.model.GetAnalyzedRecipeInstructions200ResponseParsedInstructionsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param parsedInstructions 
 * @param ingredients 
 * @param equipment 
 */


data class GetAnalyzedRecipeInstructions200Response (

    @Json(name = "parsedInstructions")
    val parsedInstructions: kotlin.collections.Set<GetAnalyzedRecipeInstructions200ResponseParsedInstructionsInner>,

    @Json(name = "ingredients")
    val ingredients: kotlin.collections.Set<GetAnalyzedRecipeInstructions200ResponseIngredientsInner>,

    @Json(name = "equipment")
    val equipment: kotlin.collections.Set<GetAnalyzedRecipeInstructions200ResponseIngredientsInner>

) {


}

